import jsPDF from 'jspdf';
import { PlanSection } from './planGenerator';
import { QuizAnswers } from './quizData';

/* ── color palette (HSL → RGB) ── */
const COLORS = {
  cream: [250, 245, 235] as [number, number, number],
  brown: [76, 40, 30] as [number, number, number],
  terracotta: [190, 115, 80] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  lightGray: [230, 225, 215] as [number, number, number],
  text: [60, 42, 30] as [number, number, number],
  textMuted: [130, 115, 100] as [number, number, number],
  gold: [210, 160, 60] as [number, number, number],
  success: [60, 150, 100] as [number, number, number],
};

function stageLabel(stage: string): string {
  if (stage === 'puppy') return 'Puppy';
  if (stage === 'senior') return 'Senior';
  return 'Adult';
}

function weightLabel(w: string): string {
  if (w === 'under20') return 'Under 20 lbs';
  if (w === '20-28') return '20–28 lbs';
  return 'Over 28 lbs';
}

function concernLabel(c: string): string {
  const map: Record<string, string> = {
    skin: 'Skin & Allergies', pulling: 'Leash Pulling', diet: 'Diet & Weight',
    breathing: 'Breathing', wellness: 'General Wellness',
  };
  return map[c] || c;
}

function activityLabel(a: string): string {
  const map: Record<string, string> = { low: 'Low', moderate: 'Moderate', active: 'Active' };
  return map[a] || a;
}

export function generatePDF(plan: PlanSection[], answers: QuizAnswers): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = 210; // page width
  const ph = 297; // page height
  const mx = 18; // margin x
  const contentW = pw - mx * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > ph - 20) {
      addFooter();
      doc.addPage();
      y = 18;
    }
  };

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.textMuted);
    doc.text('Generated by FrenchyFab.com — Your French Bulldog Care Companion', pw / 2, ph - 8, { align: 'center' });
    doc.text(`Page ${doc.getNumberOfPages()}`, pw - mx, ph - 8, { align: 'right' });
  };

  /* ── COVER PAGE ── */
  // Background
  doc.setFillColor(...COLORS.cream);
  doc.rect(0, 0, pw, ph, 'F');

  // Top accent bar
  doc.setFillColor(...COLORS.brown);
  doc.rect(0, 0, pw, 4, 'F');

  // Gold accent line
  doc.setFillColor(...COLORS.gold);
  doc.rect(0, 4, pw, 1.5, 'F');

  // Logo area
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.terracotta);
  doc.setFont('helvetica', 'bold');
  doc.text('🐾 FRENCHYFAB', pw / 2, 35, { align: 'center' });

  // Title
  doc.setFontSize(32);
  doc.setTextColor(...COLORS.brown);
  doc.setFont('helvetica', 'bold');
  doc.text('Your Personalized', pw / 2, 75, { align: 'center' });
  doc.text('Frenchie Care Plan', pw / 2, 90, { align: 'center' });

  // Decorative line
  doc.setDrawColor(...COLORS.terracotta);
  doc.setLineWidth(0.8);
  doc.line(pw / 2 - 30, 100, pw / 2 + 30, 100);

  // Profile card
  const cardY = 115;
  const cardH = 80;
  doc.setFillColor(...COLORS.white);
  doc.roundedRect(mx + 15, cardY, contentW - 30, cardH, 4, 4, 'F');
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.3);
  doc.roundedRect(mx + 15, cardY, contentW - 30, cardH, 4, 4, 'S');

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.terracotta);
  doc.setFont('helvetica', 'bold');
  doc.text('YOUR FRENCHIE\'S PROFILE', pw / 2, cardY + 12, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.text);
  doc.setFont('helvetica', 'normal');
  const profileItems = [
    `Life Stage: ${stageLabel(answers.lifeStage)}`,
    `Weight Range: ${weightLabel(answers.weight)}`,
    `Body Condition Score: ${answers.bodyCondition}/9`,
    `Activity Level: ${activityLabel(answers.activityLevel)}`,
    `Primary Concern: ${concernLabel(answers.concern)}`,
    `Environment: ${answers.environment.join(', ') || 'Not specified'}`,
  ];
  profileItems.forEach((item, i) => {
    doc.text(item, pw / 2, cardY + 24 + i * 9, { align: 'center' });
  });

  // Date
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(`Generated on ${today}`, pw / 2, 220, { align: 'center' });

  // Tagline
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.terracotta);
  doc.setFont('helvetica', 'italic');
  doc.text('Tailored recommendations for a happier, healthier Frenchie', pw / 2, 240, { align: 'center' });

  // Website
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  doc.setFont('helvetica', 'bold');
  doc.text('frenchyfab.com', pw / 2, 260, { align: 'center' });

  addFooter();

  /* ── CONTENT PAGES ── */
  doc.addPage();
  doc.setFillColor(...COLORS.cream);
  doc.rect(0, 0, pw, ph, 'F');
  y = 18;

  // Table of contents
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.brown);
  doc.setFont('helvetica', 'bold');
  doc.text('Your Care Plan Overview', mx, y + 5);
  y += 16;

  doc.setDrawColor(...COLORS.terracotta);
  doc.setLineWidth(0.5);
  doc.line(mx, y, mx + 50, y);
  y += 10;

  plan.forEach((section, i) => {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.text);
    doc.setFont('helvetica', 'normal');
    doc.text(`${section.icon}  ${section.title}`, mx + 5, y);
    doc.setTextColor(...COLORS.textMuted);
    doc.text(`${section.items.length} recommendations`, pw - mx, y, { align: 'right' });
    y += 8;
    if (i < plan.length - 1) {
      doc.setDrawColor(...COLORS.lightGray);
      doc.setLineWidth(0.15);
      doc.line(mx + 5, y - 2, pw - mx, y - 2);
    }
  });

  y += 10;
  doc.setFillColor(...COLORS.white);
  doc.roundedRect(mx, y, contentW, 20, 3, 3, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textMuted);
  doc.setFont('helvetica', 'italic');
  const disclaimerLines = doc.splitTextToSize(
    'Disclaimer: This care plan is for informational purposes only and does not replace professional veterinary advice. Always consult your veterinarian before making changes to your Frenchie\'s diet, exercise, or health regimen.',
    contentW - 10
  );
  doc.text(disclaimerLines, mx + 5, y + 7);

  addFooter();

  /* ── SECTION PAGES ── */
  plan.forEach((section) => {
    doc.addPage();
    doc.setFillColor(...COLORS.cream);
    doc.rect(0, 0, pw, ph, 'F');
    y = 18;

    // Section header
    doc.setFillColor(...COLORS.brown);
    doc.roundedRect(mx, y, contentW, 16, 3, 3, 'F');
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.white);
    doc.setFont('helvetica', 'bold');
    doc.text(`${section.icon}  ${section.title}`, mx + 6, y + 11);
    y += 24;

    // Items
    section.items.forEach((item) => {
      const isWarning = item.startsWith('⚠️');
      const lines = doc.splitTextToSize(item.replace(/^⚠️\s*/, ''), contentW - 16);
      const blockH = lines.length * 5.5 + 8;

      ensureSpace(blockH + 4);

      if (isWarning) {
        doc.setFillColor(255, 245, 230);
        doc.roundedRect(mx, y, contentW, blockH, 2, 2, 'F');
        doc.setDrawColor(220, 160, 60);
        doc.setLineWidth(0.4);
        doc.roundedRect(mx, y, contentW, blockH, 2, 2, 'S');
      } else {
        doc.setFillColor(...COLORS.white);
        doc.roundedRect(mx, y, contentW, blockH, 2, 2, 'F');
      }

      // Bullet
      const bulletColor = isWarning ? COLORS.gold : COLORS.terracotta;
      doc.setFillColor(bulletColor[0], bulletColor[1], bulletColor[2]);
      doc.circle(mx + 5, y + 5, 1.2, 'F');

      doc.setFontSize(9);
      doc.setTextColor(...COLORS.text);
      doc.setFont('helvetica', 'normal');
      doc.text(lines, mx + 10, y + 5.5);

      y += blockH + 2.5;
    });

    // Article link
    if (section.articleLink) {
      ensureSpace(14);
      y += 4;
      doc.setFillColor(...COLORS.terracotta);
      doc.roundedRect(mx, y, contentW, 10, 2, 2, 'F');
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.white);
      doc.setFont('helvetica', 'bold');
      doc.text(`📖 Read more: ${section.articleLink.label}  →  ${section.articleLink.url}`, mx + 5, y + 6.5);
      y += 14;
    }

    addFooter();
  });

  /* ── BACK PAGE ── */
  doc.addPage();
  doc.setFillColor(...COLORS.cream);
  doc.rect(0, 0, pw, ph, 'F');

  doc.setFillColor(...COLORS.brown);
  doc.rect(0, ph - 4, pw, 4, 'F');
  doc.setFillColor(...COLORS.gold);
  doc.rect(0, ph - 5.5, pw, 1.5, 'F');

  doc.setFontSize(22);
  doc.setTextColor(...COLORS.brown);
  doc.setFont('helvetica', 'bold');
  doc.text('Thank You!', pw / 2, ph / 2 - 30, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);
  doc.setFont('helvetica', 'normal');
  const thankLines = doc.splitTextToSize(
    'This care plan was generated specifically for your French Bulldog based on the information you provided. For more tips, guides, and breed-specific advice, visit us online.',
    contentW - 30
  );
  doc.text(thankLines, pw / 2, ph / 2 - 15, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.terracotta);
  doc.setFont('helvetica', 'bold');
  doc.text('frenchyfab.com', pw / 2, ph / 2 + 15, { align: 'center' });

  doc.setFontSize(9);
  doc.setTextColor(...COLORS.textMuted);
  doc.text('Follow us for daily Frenchie tips and community stories', pw / 2, ph / 2 + 25, { align: 'center' });

  addFooter();

  /* ── SAVE ── */
  doc.save('FrenchyFab-Care-Plan.pdf');
}
