// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyxsijqazzhuudhmfitw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eHNpanFhenpodXVkaG1maXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MjI3MDcsImV4cCI6MjA5MDA5ODcwN30.6Hhf8LVpZzGc1_iJDSMsqTNKR9tj2PyesE-mimx7Mlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});